apiVersion: v1
kind: PersistentVolume
metadata:
  name: kea-primary-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dhcp
  local:
    path: /kube/6d8c59a5-8b75-4a6c-80b8-973d79bf21fe
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - chimera
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kea-secondary-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dhcp
  local:
    path: /kube/6d8c59a5-8b75-4a6c-80b8-973d79bf21fe
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - archon