kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dhcp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
