- WLC DC1 Hotspot:
  - s0:
      ip: 10.200.0.0/20
      vlan: 3000
      vrf: VRF60
  - s1:
      ip: 10.200.16.0/20
      vlan: 3001
      vrf: VRF60
  - s2:
      ip: 10.200.32.0/20
      vlan: 3002
      vrf: VRF60
  - s3:
      ip: 10.200.48.0/20
      vlan: 3003
      vrf: VRF60
  - s4:
      ip: 10.200.64.0/20
      vlan: 3004
      vrf: VRF60
  - s5:
      ip: 10.200.80.0/20
      vlan: 3005
      vrf: VRF60
  - s6:
      ip: 10.200.96.0/20
      vlan: 3006
      vrf: VRF60
  - s7:
      ip: 10.200.112.0/20
      vlan: 3007
      vrf: VRF60
- WLC DC1 Stab:
  - s0:
      ip: 10.202.0.0/20
      vlan: 3010
      vrf: VRF30
  - s1:
      ip: 10.202.16.0/20
      vlan: 3011
      vrf: VRF30
  - s2:
      ip: 10.202.32.0/20
      vlan: 3012
      vrf: VRF30
  - s3:
      ip: 10.202.48.0/20
      vlan: 3013
      vrf: VRF30
  - s4:
      ip: 10.202.64.0/20
      vlan: 3014
      vrf: VRF30
  - s5:
      ip: 10.202.80.0/20
      vlan: 3015
      vrf: VRF30
  - s6:
      ip: 10.202.96.0/20
      vlan: 3016
      vrf: VRF30
  - s7:
      ip: 10.202.112.0/20
      vlan: 3017
      vrf: VRF30
- VLC DC1 NetNisse:
  - s0:
      ip: 10.220.0.0/20
      vlan: 3020
      vrf: VRF20
