- IS01:
    - IS01:
        ip: 10.1.0.0
        vlan: 100
    - IS03:
        ip: 10.3.0.0
        vlan: 300
- IS05 DC1:
    - IS05:
        ip: 10.5.0.0
        vlan: 500
    - IS06:
        ip: 10.6.0.0
        vlan: 600
    - IS02:
        ip: 10.2.0.0
        vlan: 200
    - IS17:
        ip: 10.17.0.0
        vlan: 1700
- IS07:
    - IS07:
        ip: 10.7.0.0
        vlan: 700
    - IS04:
        ip: 10.4.0.0
        vlan: 400
    - IS08:
        ip: 10.8.0.0
        vlan: 800
- IS12:
    - IS12:
        ip: 10.12.0.0
        vlan: 1200
    - IS13:
        ip: 10.13.0.0
        vlan: 1300
    - IS16:
        ip: 10.16.0.0
        vlan: 1600
- IS15 DC2:
    - IS15:
        ip: 10.15.0.0
        vlan: 1500
    - IS09:
        ip: 10.9.0.0
        vlan: 900
    - IS10:
        ip: 10.10.0.0
        vlan: 1000
    - IS11:
        ip: 10.11.0.0
        vlan: 1100
    - IS14:
        ip: 10.14.0.0
        vlan: 1400
    - IS20:
        ip: 10.20.0.0
        vlan: 2000
    - IS21:
        ip: 10.21.0.0
        vlan: 2100
- IS25 SKI:
    - IS25:
        ip: 10.25.0.0
        vlan: 2500
- DC:
    - DC:
        ip: 10.255.0.0
        vlan: 3500
